## Merge 6 bins of YLL distribution so that it does not overlap with YDIST!
## Unnormalized distributions
FKmerge FK_ATLASZPT8TEV-YLLBIN1_ptZ.dat FK_ATLASZPT8TEV-YLLBIN2_ptZ.dat FK_ATLASZPT8TEV-YLLBIN3_ptZ.dat FK_ATLASZPT8TEV-YLLBIN4_ptZ.dat FK_ATLASZPT8TEV-YLLBIN5_ptZ.dat FK_ATLASZPT8TEV-YLLBIN6_ptZ.dat > FK_ATLASZPT8TEVYDIST.dat

RETCODE=$?; if [[ $RETCODE != 0 ]]; then exit $RETCODE; fi

## Normalized distributions
## Increase total distribions and merge them

cp FK_ATLASZPT8TEVYDIST.dat FK_ATLASZPT8TEVYDIST_ptZ.dat

FKmerge FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat FK_ATLASZPT8TEV-YLLBIN1_tot.dat > FK_ATLASZPT8TEV-YLLBIN1_TOT.dat

FKmerge FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat FK_ATLASZPT8TEV-YLLBIN2_tot.dat > FK_ATLASZPT8TEV-YLLBIN2_TOT.dat

FKmerge FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat FK_ATLASZPT8TEV-YLLBIN3_tot.dat > FK_ATLASZPT8TEV-YLLBIN3_TOT.dat

FKmerge FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat FK_ATLASZPT8TEV-YLLBIN4_tot.dat > FK_ATLASZPT8TEV-YLLBIN4_TOT.dat

FKmerge FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat FK_ATLASZPT8TEV-YLLBIN5_tot.dat > FK_ATLASZPT8TEV-YLLBIN5_TOT.dat

FKmerge FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat FK_ATLASZPT8TEV-YLLBIN6_tot.dat > FK_ATLASZPT8TEV-YLLBIN6_TOT.dat

# merge them all

FKmerge FK_ATLASZPT8TEV-YLLBIN1_TOT.dat FK_ATLASZPT8TEV-YLLBIN2_TOT.dat FK_ATLASZPT8TEV-YLLBIN3_TOT.dat FK_ATLASZPT8TEV-YLLBIN4_TOT.dat FK_ATLASZPT8TEV-YLLBIN5_TOT.dat FK_ATLASZPT8TEV-YLLBIN6_TOT.dat > FK_ATLASZPT8TEVYDIST_TOT.dat

# Cleanup
# rm FK_ATLASZPT8TEV-YLLBIN*

exit 0
