#!/bin/bash
echo "# COMPOUND FK
FK: FK_CMSWCHARM_WP.dat
FK: FK_CMSWCHARM_WM.dat
OP: RATIO" > FK_CMSWCHARMRAT-COMPOUND.dat

echo "# COMPOUND FK
FK: FK_CMSWCHARM_WP.dat
FK: FK_CMSWCHARM_WM.dat
OP: ADD" > FK_CMSWCHARMTOT-COMPOUND.dat

# Cleanup
exit 0
